<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.4.2';
$moduleRevision = '3f7873ce3d3d7929c592cf7bf594b259e12a4f47';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/OpenStack_VPS_For_WHMCS';